"""change type hint of Author.book field sqlalchemy model.

Revision ID: b231d059f100
Revises: bb9246bd2e4b
Create Date: 2024-08-08 13:55:06.128009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b231d059f100'
down_revision: Union[str, None] = 'bb9246bd2e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
