"""move cascade parameter from Book model to Author model.

Revision ID: e159d0e74d6f
Revises: cb6ab19e2439
Create Date: 2024-08-06 16:04:29.030218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e159d0e74d6f'
down_revision: Union[str, None] = 'cb6ab19e2439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
