services:
  app:
    build: .
    depends_on:
      db-main:
        condition: service_healthy
      db-test:
        condition: service_healthy
    ports:
        - 8080:8080
    env_file:
        - .env

  db-main:
    image: postgres:14
    restart: always
    ports:
      - 5431:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    volumes:
      - library-db:/var/lib/postgresql/data

  db-test:
    image: postgres:14
    restart: always
    ports:
      - 5430:5432
    env_file:
        - .env
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username ${TEST_DB_USER} -d ${TEST_DB_NAME}"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 6380:6379
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    

volumes:
  library-db: