"""change sqlalchemy models.

Revision ID: 36f64fc9ad94
Revises: cfece190c9e1
Create Date: 2024-09-02 10:44:01.898136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f64fc9ad94'
down_revision: Union[str, None] = 'cfece190c9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('description', sa.String(), nullable=False))
    op.add_column('author', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('author', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index(op.f('ix_author_fullname'), 'author', ['fullname'], unique=True)
    op.drop_column('author', 'last_name')
    op.drop_column('author', 'first_name')
    op.drop_column('author', 'patronymic')
    op.add_column('book', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('book', 'genre',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('book', 'publish_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('book', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_book_publish_date', table_name='book')
    op.drop_constraint('book_author_id_fkey', 'book', type_='foreignkey')
    op.create_foreign_key(None, 'book', 'author', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.create_foreign_key('book_author_id_fkey', 'book', 'author', ['author_id'], ['id'])
    op.create_index('ix_book_publish_date', 'book', ['publish_date'], unique=False)
    op.alter_column('book', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('book', 'publish_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('book', 'genre',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.drop_column('book', 'created_at')
    op.add_column('author', sa.Column('patronymic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('author', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('author', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_author_fullname'), table_name='author')
    op.alter_column('author', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('author', 'created_at')
    op.drop_column('author', 'description')
    # ### end Alembic commands ###
