"""remove author fullname unique constraint.

Revision ID: 406072e158ee
Revises: 4a7384402322
Create Date: 2024-09-11 11:24:32.704489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406072e158ee'
down_revision: Union[str, None] = '4a7384402322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_author_fullname', table_name='author')
    op.create_index(op.f('ix_author_fullname'), 'author', ['fullname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_author_fullname'), table_name='author')
    op.create_index('ix_author_fullname', 'author', ['fullname'], unique=True)
    # ### end Alembic commands ###
