"""add fields to author and book models.

Revision ID: cfece190c9e1
Revises: b231d059f100
Create Date: 2024-08-12 10:14:27.761665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfece190c9e1'
down_revision: Union[str, None] = 'b231d059f100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('author', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('author', sa.Column('patronymic', sa.String(), nullable=True))
    op.add_column('author', sa.Column('birth_date', sa.Date(), nullable=False))
    op.add_column('author', sa.Column('death_date', sa.Date(), nullable=True))
    op.drop_column('author', 'death_year')
    op.drop_column('author', 'birth_year')
    op.add_column('book', sa.Column('genre', sa.String(length=80), nullable=False))
    op.add_column('book', sa.Column('language', sa.String(length=50), nullable=False))
    op.add_column('book', sa.Column('publish_date', sa.Date(), nullable=False))
    op.drop_index('ix_book_publish_year', table_name='book')
    op.create_index(op.f('ix_book_publish_date'), 'book', ['publish_date'], unique=False)
    op.drop_column('book', 'publish_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('publish_year', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_book_publish_date'), table_name='book')
    op.create_index('ix_book_publish_year', 'book', ['publish_year'], unique=False)
    op.drop_column('book', 'publish_date')
    op.drop_column('book', 'language')
    op.drop_column('book', 'genre')
    op.add_column('author', sa.Column('birth_year', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('author', sa.Column('death_year', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('author', 'death_date')
    op.drop_column('author', 'birth_date')
    op.drop_column('author', 'patronymic')
    op.drop_column('author', 'last_name')
    op.drop_column('author', 'first_name')
    # ### end Alembic commands ###
